# Generated by Django 6.1.1 on 2026-09-14 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # `__first__` rather than a migration name: this plugin is a separate repository, and
    # mutint-core is free to renumber, squash or collapse its own history without knowing
    # this file exists. The model named below is created in its app's *first* migration,
    # which is all a foreign key to it needs.
    #
    # `makemigrations` emits concrete names and will never emit this; regenerating this file
    # reverts the sentinel silently. Re-apply it when you do.
    dependencies = [
        ('mutint_experiment', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefsniffRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('read_file', models.CharField(max_length=255)),
                ('reads_requested', models.PositiveIntegerField()),
                ('reads_sampled', models.PositiveIntegerField(default=0)),
                ('bases_sampled', models.BigIntegerField(default=0)),
                ('contact_email', models.CharField(blank=True, max_length=254)),
                ('blast_rid', models.CharField(blank=True, max_length=64)),
                ('blast_hits', models.JSONField(default=list)),
                ('note', models.TextField(blank=True)),
                ('best_accession', models.CharField(blank=True, max_length=64)),
                ('best_organism', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('finished', 'Finished'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('task_result_id', models.CharField(blank=True, max_length=64)),
                ('log', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refsniff_runs', to='mutint_experiment.experiment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
