# Generated by Django 6.1.1 on 2026-09-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutint_refsniff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refsniffrun',
            name='bases_sampled',
        ),
        migrations.RemoveField(
            model_name='refsniffrun',
            name='blast_hits',
        ),
        migrations.RemoveField(
            model_name='refsniffrun',
            name='blast_rid',
        ),
        migrations.RemoveField(
            model_name='refsniffrun',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='refsniffrun',
            name='reads_requested',
        ),
        migrations.RemoveField(
            model_name='refsniffrun',
            name='reads_sampled',
        ),
        migrations.AddField(
            model_name='refsniffrun',
            name='accession',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='refsniffrun',
            name='bases_sketched',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refsniffrun',
            name='hits',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='refsniffrun',
            name='read_url',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='refsniffrun',
            name='reads_sketched',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
